name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: FizzBuzz Test
      id: fizzbuzz-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: FizzBuzz Test
        setup-command: npm install
        command: npm run test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        FIZZBUZZ-TEST_RESULTS: "${{steps.fizzbuzz-test.outputs.result}}"
      with:
        runners: fizzbuzz-test
